# Generated by Django 5.1.1 on 2024-10-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='choices',
            field=models.TextField(),
        ),
    ]
