# Generated by Django 5.1.1 on 2024-10-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_quiz_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='choices',
            field=models.JSONField(),
        ),
    ]
